name: chimeramix
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - black
  - python=3.10
  - pip
  - pylint
  - rope
  - torchvision
  - pytorch
  - pytorch-cuda=11.8
  - pip:
      - numpy
      - matplotlib
      - Pillow
      - lightning==1.9
      - torchinfo
      - wandb
      - hydra-core
      - hydra-slurm-rich-launcher
      - scikit-image